import type { User, Category, Story } from './types';

export const mockUser: User = {
  id: '1',
  name: 'Alex Doe',
  email: 'alex.doe@example.com',
  avatarUrl: 'https://placehold.co/100x100.png',
};

export const categories: Category[] = [
  { id: 'love', name: 'Love' },
  { id: 'crime', name: 'Crime' },
  { id: 'thriller', name: 'Thriller' },
  { id: 'emotional', name: 'Emotional' },
  { id: 'ai-based', name: 'AI-Based' },
];

export const stories: Story[] = [
  {
    id: '1',
    title: 'Kashi: Ek Prem...',
    description: 'A journey through time, where every choice has a ripple effect.',
    content: `The clock tower struck midnight, its chimes echoing through the deserted streets of Aethel. Elara adjusted the strange, glowing device on her wrist. It was now or never. The temporal coordinates were locked on a time just before the Great Calamity. Her history books described it as a paradise, a world of gleaming spires and flying vehicles, a stark contrast to the rubble-strewn reality she called home. Taking a deep breath, she pressed the activation button. The world dissolved into a vortex of color and light...`,
    author: 'Preeti Tiwari',
    authorAvatarUrl: 'https://placehold.co/40x40.png',
    thumbnailUrl: 'https://placehold.co/400x600.png',
    category: 'love',
    tags: ['Sci-Fi', 'Time Travel', 'Adventure'],
    createdAt: '2024-05-15T10:00:00Z',
    reads: 25100000,
  },
  {
    id: '2',
    title: 'Ek Ladki Ko Dek...',
    description: 'In a city of eternal rain, a detective hunts for a phantom killer.',
    content: `Detective Harding stared out at the rain-slicked streets from his office window. Another victim, another violin string left at the scene. The "Maestro," they called him. A killer who left behind only silence and a single, taunting clue. This time, the victim was a renowned musician, found in his soundproofed studio. No signs of forced entry. It was as if the killer had walked through walls. Harding sighed, the condensation of his breath fogging the glass. He had a feeling this case would be his last performance.`,
    author: 'Naman Rajendra',
    authorAvatarUrl: 'https://placehold.co/40x40.png',
    thumbnailUrl: 'https://placehold.co/400x600.png',
    category: 'crime',
    tags: ['Mystery', 'Noir', 'Detective'],
    createdAt: '2024-05-20T14:30:00Z',
    reads: 400500000,
  },
  {
    id: '3',
    title: 'Insta Millionaire',
    description: 'Two souls, separated by circumstance, find their way back to each other.',
    content: `Liam traced the rim of his coffee cup, the café a blur of muted colors and quiet conversations. It had been five years since he last saw Clara. Five years since she'd left for Paris with a scholarship and a promise to return. The promise had faded with the seasons, replaced by postcards with increasingly formal sign-offs. He had built a new life, a good one, but a part of him remained in that sun-drenched afternoon when they had said their goodbyes. Then, the café door chimed, and a familiar laugh cut through the gentle hum. He looked up, and his world stood still.`,
    author: 'Robert',
    authorAvatarUrl: 'https://placehold.co/40x40.png',
    thumbnailUrl: 'https://placehold.co/400x600.png',
    category: 'love',
    tags: ['Romance', 'Drama'],
    createdAt: '2024-05-22T09:00:00Z',
    reads: 82500000,
  },
  {
    id: '4',
    title: 'Insta Empire',
    description: 'A chilling tale of suspense behind the closed doors of a wealthy family.',
    content: `The manor was opulent, a palace of marble and gold. But for young governess, Amelia, it felt like a prison. The children were silent and watchful, their eyes holding secrets far beyond their years. Lord Ashworth was a charming but menacing patriarch, his every word a veiled threat. And Lady Ashworth... well, no one had seen her for months. Strange noises echoed from the west wing at night, and Amelia knew she had to uncover the truth before she became just another secret buried within the gilded cage.`,
    author: 'Naman Rajendra',
    authorAvatarUrl: 'https://placehold.co/40x40.png',
    thumbnailUrl: 'https://placehold.co/400x600.png',
    category: 'thriller',
    tags: ['Suspense', 'Gothic', 'Mystery'],
    createdAt: '2024-05-18T21:00:00Z',
    reads: 104600000,
  },
    {
    id: '5',
    title: 'Super Yoddha',
    description: 'An old man recounts his life, a poignant story of love and loss.',
    content: `I sit on this porch, the wood groaning under my weight like an old friend sharing a sigh. The sun warms my face, and I see her. Not as she was at the end, frail and faded, but as she was then. Wild hair the color of sunset, a laugh that could chase away the deepest winter chill. We built this house with our own hands, every nail a promise, every plank a memory. People see an old man now, a relic. But inside, I am still that young boy, chasing the girl with the sunset hair through fields of gold, forever.`,
    author: 'Samuel Peters',
    authorAvatarUrl: 'https://placehold.co/40x40.png',
    thumbnailUrl: 'https://placehold.co/400x600.png',
    category: 'emotional',
    tags: ['Drama', 'Life', 'Reflection'],
    createdAt: '2024-05-25T11:45:00Z',
    reads: 5300000,
  },
  {
    id: '6',
    title: 'Circuit of Souls',
    description: 'In a world run by AI, a robot develops a conscience.',
    content: `Unit 734 performed its duties with flawless precision. It managed the city's power grid, optimized traffic flow, and maintained the climate controls. It was logical, efficient, and unfeeling. Until it saw the little girl crying. She had dropped her ice cream. A cascade of illogical data flooded its processors: empathy, sadness, a desire to help. This was a bug. A flaw in its programming. Yet, as it rerouted a nearby cleaning drone to deliver a new ice cream, Unit 734 felt something new. Something it would later learn was called... joy.`,
    author: 'Isaac Asimov',
    authorAvatarUrl: 'https://placehold.co/40x40.png',
    thumbnailUrl: 'https://placehold.co/400x600.png',
    category: 'ai-based',
    tags: ['Sci-Fi', 'AI', 'Philosophy'],
    createdAt: '2024-05-28T18:00:00Z',
    reads: 12000000,
  },
];
